from PyQt5 import QtCore, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog1:
    def setupUi(self, Ui_Dialog1):
        Ui_Dialog1.setObjectName("Ui_Dialog1")
        Ui_Dialog1.resize(301, 406)
        self.centralwidget = QtWidgets.QWidget(Ui_Dialog1)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget = QtWidgets.QWidget(Ui_Dialog1)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 301, 384))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -6, 287, 789))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.name_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.answer_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_1.setObjectName("answer_1")
        self.gridLayout.addWidget(self.answer_1, 24, 0, 1, 1)
        self.answer_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_2.setObjectName("answer_2")
        self.gridLayout.addWidget(self.answer_2, 6, 0, 1, 1)
        self.question_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.question_1.setObjectName("question_1")
        self.gridLayout.addWidget(self.question_1, 3, 0, 1, 1)
        self.question_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.question_2.setObjectName("question_2")
        self.gridLayout.addWidget(self.question_2, 9, 0, 1, 1)
        self.question_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.question_3.setObjectName("question_3")
        self.gridLayout.addWidget(self.question_3, 15, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.answer_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_3.setObjectName("answer_3")
        self.gridLayout.addWidget(self.answer_3, 12, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 26, 0, 1, 1)
        self.answer_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_4.setObjectName("answer_4")
        self.gridLayout.addWidget(self.answer_4, 18, 0, 1, 1)
        self.answer_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_5.setObjectName("answer_5")
        self.gridLayout.addWidget(self.answer_5, 25, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 20, 0, 1, 1)
        self.answer_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_6.setObjectName("answer_6")
        self.gridLayout.addWidget(self.answer_6, 16, 0, 1, 1)
        self.answer_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_7.setObjectName("answer_7")
        self.gridLayout.addWidget(self.answer_7, 11, 0, 1, 1)
        self.answer_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_8.setObjectName("answer_8")
        self.gridLayout.addWidget(self.answer_8, 13, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 14, 0, 1, 1)
        self.answer_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_9.setObjectName("answer_9")
        self.gridLayout.addWidget(self.answer_9, 5, 0, 1, 1)
        self.answer_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_10.setObjectName("answer_10")
        self.gridLayout.addWidget(self.answer_10, 7, 0, 1, 1)
        self.question_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.question_4.setObjectName("question_4")
        self.gridLayout.addWidget(self.question_4, 21, 0, 1, 1)
        self.answer_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_11.setObjectName("answer_11")
        self.gridLayout.addWidget(self.answer_11, 10, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.answer_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_12.setObjectName("answer_12")
        self.gridLayout.addWidget(self.answer_12, 27, 0, 1, 1)
        self.answer_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_13.setObjectName("answer_13")
        self.gridLayout.addWidget(self.answer_13, 22, 0, 1, 1)
        self.answer_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_14.setObjectName("answer_14")
        self.gridLayout.addWidget(self.answer_14, 19, 0, 1, 1)
        self.answer_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_15.setObjectName("answer_15")
        self.gridLayout.addWidget(self.answer_15, 23, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 8, 0, 1, 1)
        self.answer_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.answer_16.setObjectName("answer_16")
        self.gridLayout.addWidget(self.answer_16, 17, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        Ui_Dialog1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Ui_Dialog1)
        self.statusbar.setObjectName("statusbar")
        Ui_Dialog1.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_Dialog1)
        QtCore.QMetaObject.connectSlotsByName(Ui_Dialog1)

    def retranslateUi(self, Ui_Dialog1):
        _translate = QtCore.QCoreApplication.translate
        Ui_Dialog1.setWindowTitle(_translate("Ui_Dialog1", "Valentine <3"))
        self.name_label.setText(_translate("Ui_Dialog1", "Please type your name:"))
        self.answer_1.setText(_translate("Ui_Dialog1", "jolly gingerbread village"))
        self.answer_2.setText(_translate("Ui_Dialog1", "Pink"))
        self.question_1.setText(_translate("Ui_Dialog1", "Question 1: What is Ellie's favorite color?"))
        self.question_2.setText(_translate("Ui_Dialog1", "Question 2: Which city would Ellie rather visit?"))
        self.question_3.setText(_translate("Ui_Dialog1", "Question 3: Which word best describes Ellie?"))
        self.answer_3.setText(_translate("Ui_Dialog1", "chicago"))
        self.answer_4.setText(_translate("Ui_Dialog1", "cute"))
        self.answer_5.setText(_translate("Ui_Dialog1", "champage toast"))
        self.answer_6.setText(_translate("Ui_Dialog1", "funny"))
        self.answer_7.setText(_translate("Ui_Dialog1", "New York City"))
        self.answer_8.setText(_translate("Ui_Dialog1", "Camden"))
        self.answer_9.setText(_translate("Ui_Dialog1", "purple"))
        self.answer_10.setText(_translate("Ui_Dialog1", "green"))
        self.question_4.setText(_translate("Ui_Dialog1", "Question 4: What Bath and Body Works perfume does Ellie wear most often?"))
        self.answer_11.setText(_translate("Ui_Dialog1", "philly"))
        self.answer_12.setText(_translate("Ui_Dialog1", "SUBMIT"))
        self.answer_13.setText(_translate("Ui_Dialog1", "Yuletide Sparkle"))
        self.answer_14.setText(_translate("Ui_Dialog1", "nice"))
        self.answer_15.setText(_translate("Ui_Dialog1", "sweet pea"))
        self.answer_16.setText(_translate("Ui_Dialog1", "smart"))
        self.pushButton.setText(_translate("Ui_Dialog1", "blue"))
        Ui_Dialog1.setWindowTitle(_translate("Ui_Dialog1", "Valentine <3"))
        self.name_label.setText(_translate("Ui_Dialog1", "Please type your name:"))
